### ISSUE TITLE
Weird behavior with FloodgatePlayer.getDeviceOs

### ISSUE THREAD

**Issue by xenorio** [Tim203/Floodgate#10]
The FloodgatePlayer.getDeviceOs function returns an object of type DeviceOs. But the only type you can import while having floodgate common and spigot as dependencies is DeviceOS. Both are supposed to be in org.geysermc.floodgate.util

DeviceOs can also not be cast to DeviceOS

When manually importing DeviceOs by adding "import org.geysermc.floodgate.util.DeviceOs" my IDE tells me that it cannot be resolved

Am i missing a dependency? I definitely use floodgate 2.0, common and spigot.

**Comment by Tim203** [comment]
Unless you already compiled Floodgate you also need to use my Geyser fork: https://github.com/Tim203/Geyser
After you compiled Geyser common and Floodgate everything should work as expected.

**Comment by xenorio** [comment]
i am using self-compiled floodgate already. and to compile that, i needed to compile your geyser fork too. so i am using both.

also, they work just fine running on a server. i can even verify that it's your fork because i can send forms there. still, i'm having this problem with the api.

**Comment by Camotoy** [comment]
That file is present under the `org.geysermc:common:1.2.0-SNAPSHOT` dependency.

**Comment by xenorio** [comment]
Which is in my external libraries:

![](https://i.imgur.com/7guChRy.png)

But i am still unable to use DeviceOs, only DeviceOS:

![](https://i.imgur.com/5b1o5GQ.png)

**Comment by Tim203** [comment]
Are you still having this issue?
