### ISSUE TITLE
Bedrock Coustom Skins not visible in Java Edition

### ISSUE THREAD

**Issue by RehanPlayz** [Tim203/Floodgate#4]
A way for Java Players to see Coustom Bedrock Skins

**Comment by j5155** [comment]
If you mean Character Creator ones I think this is impossible because of things like bedrock players blinking
What it might be interesting to do is have a "/geyser skin" command that lets you pick from a few that work i.e. top 20 skins on namemc or something, or choose a Java player's skin

**Comment by RehanPlayz** [comment]
I have my own Coustom Made Skin (
![pmcskin3d-steve_5](https://user-images.githubusercontent.com/63925635/99142305-dfe76100-2664-11eb-893d-16b91c4f850a.png))

**Comment by Hellohi3654** [comment]
> If you mean Character Creator ones I think this is impossible because of things like bedrock players blinking
> What it might be interesting to do is have a "/geyser skin" command that lets you pick from a few that work i.e. top 20 skins on namemc or something, or choose a Java player's skin

The Skinrestorer plugin would be a good fix

**Comment by Tim203** [comment]
Have you tried Floodgate 2.0, and if you did, do you still have this issue?
