### ISSUE TITLE
Cant build the floodgate-2.0 branch

### ISSUE THREAD

**Issue by MrClean1337** [Tim203/Floodgate#8]
I just want to use the floodgate-2.0 branch, but I cant build that with IntelliJ.

I just cloned this repo, downloaded the dependencies automatically and run the commands
1. `git submodule update --init --recursive`
2. `mvn clean install`

And I got this error https://pastebin.com/bU9C2mgq

What do I need to compile that repo ?

**Comment by Maescool** [comment]
You need to have locally build https://github.com/Tim203/Geyser first, then you can build this.

**Comment by MrClean1337** [comment]
Thank you for that, but how to add Tim's floodgate-2.0 as a maven dependency ?

This will throw "Missing artifact" for both of them:
`		<dependency>
			<groupId>org.geysermc</groupId>
			<artifactId>floodgate-common</artifactId>
			<version>2.0-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>org.geysermc</groupId>
			<artifactId>floodgate-spigot</artifactId>
			<version>2.0-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>`

Thanks 👍

**Comment by solarft** [comment]
How do I locally build this repository?

**Comment by MrClean1337** [comment]
> How do I locally build this repository?

1. Do this https://github.com/Tim203/Geyser#compiling
2. After you built it locally, do this 

`git clone https://github.com/Tim203/Floodgate.git`
Locate to the repo root dir ..
`git submodule update --init --recursive`
`mvn clean install`

Then you got it

**Comment by KiwiPopper** [comment]
Thanks, got it working. But, is this for bungeecord or spigot?

**Comment by KiwiPopper** [comment]
> > How do I locally build this repository?
> 
> 1. Do this https://github.com/Tim203/Geyser#compiling
> 2. After you built it locally, do this
> 
> `git clone https://github.com/Tim203/Floodgate.git`
> Locate to the repo root dir ..
> `git submodule update --init --recursive`
> `mvn clean install`
> 
> Then you got it

Thanks, got it working. But, is this for bungeecord or spigot?
